# Initialize zsh completions
autoload -U compinit;
compinit

# Initialize bash completions (for when no zsh support exists, like for pipx)
autoload -U bashcompinit;
bashcompinit

# Make dotfiles available for completion (e.g. `.git` folders won't show otherwise)
_comp_options+=(globdots)

pushd $DOTFILES > /dev/null
source $DOTFILES/alias.sh
source $DOTFILES/rc.sh
popd > /dev/null

setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt INTERACTIVE_COMMENTS # Ignore comments in interactive mode.
