FROM debian:12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  tinyproxy \
  && rm -rf /var/lib/apt/lists/*

COPY tinyproxy.conf /etc/tinyproxy/tinyproxy.conf
COPY tinyproxy-filter /etc/tinyproxy/filter

EXPOSE 8888
CMD ["tinyproxy", "-d"]
