## kubectl
alias k='kubectl'
alias kcg='kubectl config get-contexts'
alias kcu='kubectl config use-context'
alias kde='kubectl describe'
alias kdep='kubectl describe pod'
alias kdl='kubectl delete'
alias kdlp='kubectl delete pod'
alias keit='kubectl exec -it'
alias kg='kubectl get'
alias kgd='kubectl get deploy'
alias kgp='kubectl get po'
alias kgs='kubectl get svc'
alias kgss='kubectl get sts'
alias klf='kubectl logs -f'
alias kpf='kubectl port-forward'
