alias tp='telepresence'
alias tpc='telepresence connect'
alias tpi='telepresence intercept'
alias tple='telepresence leave'
alias tpli='telepresence list'
alias tpq='telepresence quit'
alias tps='telepresence status'
alias tpu='telepresence uninstall'
