# aliases
source $DOTFILES/aliases/aliases.sh
[ -f ~/.aliases ] && source ~/.aliases

# starship
eval "$(starship init zsh)"
# fnm
eval "$(fnm env --use-on-cd)"
# deno
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
# broot
source ~/.config/broot/launcher/bash/br

# completion
autoload -U compinit; compinit
_comp_options+=(globdots) # With hidden files
# source /my/path/to/zsh/completion.zsh
eval "$(op completion zsh)"; compdef _op op
